Bump typing-extensions and typeapi (#60)
* Bump the permitted typeapi version

* typing-extensions version depending on Python version

* Enter changelog entry

* PR 60

* Fix dependency specification and add changelogs

* Conform to previous Tomli format

* Bump poetry-core build backend, avoid `six.moves` error

```
> import six.moves.urllib.parse as urllib_parse
ModuleNotFoundError: No module named 'six.moves'
```

* `slap test` stops erroring on py3.10

* The assert does not fail in any supported Python version, so we just
remove it

* types is not used anymore, so we remove it

* Drop support for python 3.6 and 3.7

* bin dev dependencies and run black fmt

* add flake8 ignore

* pin black 23 for now to reduce diff

* push docs on develop only

---------

Co-authored-by: Niklas Rosenstein <rosensteinniklas@gmail.com>